bookshelf/book/urls.py
from django.urls import path
from . import views

# register the app namespace
# URL NAMES
app_name = 'book'

urlpatterns = [
    path('', views.cover_view, name='cover'),
    path('var/', views.variable_view, name='var'),
]

bookshelf/bookshelf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),
]

handler404 = 'bookshelf.views.mod_404'

bookshelf/book/models.py
from django.db import models

# Create your models here.

bookshelf/shelf/models.py
from django.db import models

# Create your models here.

bookshelf/book/views.py
from django.shortcuts import render

# Create your views here.
def cover_view(request):
    # <app>/templates/<app>/cover.html
    return render(request, 'book/cover.html')

def variable_view(request):
    dict1 = {'first_name': 'Rosalin', 'last_name':'Franklin', 'some_list':[1,2,3], 'some_dict':{'inside_key':'inside_value'}, 'user_logged_in': True}
    return render(request, 'book/variable.html', context=dict1)

bookshelf/bookshelf/views.py
from django.shortcuts import render

def mod_404(request, exception):
    return render(request, '404.html', status=404)

bookshelf/shelf/views.py
from django.shortcuts import render

# Create your views here.

bookshelf/book/templates/book/cover.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <h1>COVER TEMPLATE CONNECTED</h1>
    <h1><a href="{% url 'book:var' %}">Link to variable</a>  </h1>
    <img src="{% static 'book/i.jpg' %}" alt="cover image">
{% endblock %}

bookshelf/book/templates/book/variable.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>VARIABLE.HTML</h1>
    {#  FILTERS  #}
    <h2>{{first_name | lower | capfirst}} {{first_name | length}} {{last_name | capfirst}}</h2>

    {#  VARIABLES  #}
    <h2>{{some_list.0}}</h2>
    <h2>{{some_dict.inside_key}}</h2>

    {#  TAGS  #}
    <ul>
    {% for item in some_list %}
        {% if item == 2 %}
            <li> TWO {{item}}</li> 
        {% else %}
            <li> Item {{item}}</li> 
        {% endif %}
    {% endfor %}
    </ul>
    <ul>
    {% for k,v in some_dict.items %}
        <li>{{k}} # {{v}}</li> 
    {% endfor %}
    </ul>

    {%if user_logged_in%}
        <h3>Welcome back, {{first_name}}! You're logged in</h3>
    {% endif %}

</body>
</html>

bookshelf/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>base title</title>
</head>
<body>
    
<h1>BASE ABOVE BLOCK</h1>
{% block content %}

{% endblock content %}
<h1>BASE BELOW BLOCK</h1>

</body>
</html>